server:
  port: 8087
spring:
  application:
    name: smartzuul-liu
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8889/eureka
zuul:
  routes:
#    demo:
#      path: /demo/**
#      serviceId: DEMO
#      stripPrefix: true
    baidu:
      path: /baidu/**
      url: https://www.baidu.com
management:
  security:
    enabled: false